dataset:
  defects_folder: ./../data/Defects/
  defects_masks_folder: ./../data/DefectsMasks/
  splits: [.5, .25, .25]
model:
  epochs: 5
  batch_size: 4
  learning_rate: 1e-4
  optimizer: adam
  scheduler: none
  only_test: False
logger:
  log_dir: ./log
  experiment_name: train_harmonization
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 3
  mode: min