dataset:
  defects_folder: ./../data/Defects/
  defects_masks_folder: ./../data/DefectsMasks/
  splits: [.5, .25, .25]
model:
  name: tsaiv1
  epochs: 200
  batch_size: 4
  learning_rate: 1e-4
  optimizer: adamw
  scheduler: plateau
  only_test: False
logger:
  log_dir: ./log
  experiment_name: train_tsai
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 3
  mode: min
  